"C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\bin\runnerw.exe" C:\Python27\python.exe C:/Users/diego/OneDrive/Projetos/sistema_contabil/manage.py runserver localhost:8000
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:11:45
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 15:11:49] "GET / HTTP/1.1" 200 14491
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 200 23739
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 121260
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 200 85589
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 200 89933
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 36868
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 200 470591
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 200 3037
[10/Jan/2017 15:11:50] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 200 9773
[10/Jan/2017 15:11:51] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 200 30834
[10/Jan/2017 15:11:51] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 200 8007
[10/Jan/2017 15:11:51] "GET /arquivos_estaticos/icones/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 56780
Not Found: /favicon.ico
Not Found: /favicon.ico
[10/Jan/2017 15:11:51] "GET /favicon.ico HTTP/1.1" 404 4672
[10/Jan/2017 15:12:04] "GET /entidade/adicionar HTTP/1.1" 301 0
[10/Jan/2017 15:12:04] "GET /entidade/adicionar/ HTTP/1.1" 200 277599
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 200 4247
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 200 3886
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 200 3890
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 200 1960
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 200 10731
[10/Jan/2017 15:12:04] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 200 82480
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 200 34459
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/scripts/padrao/controle_botoes.js HTTP/1.1" 200 159
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.css HTTP/1.1" 200 1160
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.js HTTP/1.1" 200 3386
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/angular-1.5.8/angular.min.js HTTP/1.1" 200 160366
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/scripts/protocolo/protocolo.js HTTP/1.1" 200 2620
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 200 3568
[10/Jan/2017 15:12:05] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 200 3036
[10/Jan/2017 15:12:18] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/images/ui-icons_444444_256x240.png HTTP/1.1" 200 6992
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:16:20
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 15:16:34] "GET /entidade/adicionar/ HTTP/1.1" 200 277595
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:20:04
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:20:11
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:24:46
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:26:57
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:27:13
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:27:50
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x04CFC330>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
entidade.Documento.criado_por: (fields.E304) Reverse accessor for 'Documento.criado_por' clashes with reverse accessor for 'Documento.entidade'.
	HINT: Add or change a related_name argument to the definition for 'Documento.criado_por' or 'Documento.entidade'.
entidade.Documento.criado_por: (fields.E304) Reverse accessor for 'Documento.criado_por' clashes with reverse accessor for 'Documento.finalizado_por'.
	HINT: Add or change a related_name argument to the definition for 'Documento.criado_por' or 'Documento.finalizado_por'.
entidade.Documento.entidade: (fields.E304) Reverse accessor for 'Documento.entidade' clashes with reverse accessor for 'Documento.criado_por'.
	HINT: Add or change a related_name argument to the definition for 'Documento.entidade' or 'Documento.criado_por'.
entidade.Documento.entidade: (fields.E304) Reverse accessor for 'Documento.entidade' clashes with reverse accessor for 'Documento.finalizado_por'.
	HINT: Add or change a related_name argument to the definition for 'Documento.entidade' or 'Documento.finalizado_por'.
entidade.Documento.finalizado_por: (fields.E304) Reverse accessor for 'Documento.finalizado_por' clashes with reverse accessor for 'Documento.criado_por'.
	HINT: Add or change a related_name argument to the definition for 'Documento.finalizado_por' or 'Documento.criado_por'.
entidade.Documento.finalizado_por: (fields.E304) Reverse accessor for 'Documento.finalizado_por' clashes with reverse accessor for 'Documento.entidade'.
	HINT: Add or change a related_name argument to the definition for 'Documento.finalizado_por' or 'Documento.entidade'.

System check identified 6 issues (0 silenced).
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 15:35:42
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
January 10, 2017 - 15:37:41
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 18:12:32
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 18:15:13] "GET /entidade/adicionar/ HTTP/1.1" 200 277595
[10/Jan/2017 18:15:35] "GET /entidade/cadastro HTTP/1.1" 301 0
[10/Jan/2017 18:15:36] "GET /entidade/cadastro/ HTTP/1.1" 200 35743
[10/Jan/2017 18:15:36] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[10/Jan/2017 18:15:36] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[10/Jan/2017 18:15:36] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[10/Jan/2017 18:15:36] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[10/Jan/2017 18:15:37] "GET /arquivos_estaticos/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[10/Jan/2017 18:15:41] "GET /entidade/visualizar/5 HTTP/1.1" 301 0
Olha o supervisor:  2
[10/Jan/2017 18:15:41] "GET /entidade/visualizar/5/ HTTP/1.1" 200 278229
Internal Server Error: /entidade/visualizar/2/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /entidade/visualizar/2/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
Olha o supervisor: [10/Jan/2017 18:15:50] "GET /entidade/visualizar/2/ HTTP/1.1" 500 65544
 Olha o supervisor: Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
[10/Jan/2017 18:15:55] "GET /entidade/visualizar/3/ HTTP/1.1" 500 65993
[10/Jan/2017 18:16:06] "GET /entidade/visualizar/3 HTTP/1.1" 301 0
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 784, in visualizar_entidade
    print "Olha o supervisor: ",cliente.responsavel_cliente.id
AttributeError: 'NoneType' object has no attribute 'id'
 Olha o supervisor: [10/Jan/2017 18:16:07] "GET /entidade/visualizar/3/ HTTP/1.1" 500 66153

Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 18:16:54
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 812, in visualizar_entidade
    'responsavel_cliente': cliente.responsavel_cliente.id,
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 812, in visualizar_entidade
    'responsavel_cliente': cliente.responsavel_cliente.id,
AttributeError: 'NoneType' object has no attribute 'id'
[10/Jan/2017 18:16:55] "GET /entidade/visualizar/3/ HTTP/1.1" 500 66226
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 18:17:18
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 812, in visualizar_entidade
    'responsavel_cliente': cliente.responsavel_cliente.id,
AttributeError: 'NoneType' object has no attribute 'id'
Internal Server Error: /entidade/visualizar/3/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\diego\OneDrive\Projetos\sistema_contabil\entidade\views.py", line 812, in visualizar_entidade
    'responsavel_cliente': cliente.responsavel_cliente.id,
AttributeError: 'NoneType' object has no attribute 'id'
[10/Jan/2017 18:20:34] "GET /entidade/visualizar/3/ HTTP/1.1" 500 65931
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 18:22:59
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 18:29:15] "GET /entidade/visualizar/3/ HTTP/1.1" 200 279782
[10/Jan/2017 18:29:15] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:15] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:15] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.css HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/angular-1.5.8/angular.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/scripts/protocolo/protocolo.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/scripts/padrao/controle_botoes.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:16] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:17] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[10/Jan/2017 18:29:17] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[10/Jan/2017 18:29:17] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[10/Jan/2017 18:33:51] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/images/ui-icons_444444_256x240.png HTTP/1.1" 304 0
[10/Jan/2017 18:38:17] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/images/ui-icons_555555_256x240.png HTTP/1.1" 200 6988
[10/Jan/2017 18:50:50] "GET /entidade/visualizar/3/ HTTP/1.1" 200 280040
[10/Jan/2017 18:51:05] "GET /entidade/cadastro/ HTTP/1.1" 200 35743
[10/Jan/2017 18:51:05] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[10/Jan/2017 18:51:05] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[10/Jan/2017 18:51:05] "GET /arquivos_estaticos/datatable/datatables/media/js/jquery.dataTables.min.js HTTP/1.1" 404 1799
[10/Jan/2017 18:51:05] "GET /arquivos_estaticos/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js HTTP/1.1" 404 1877
[10/Jan/2017 18:51:08] "GET /entidade/visualizar/5/ HTTP/1.1" 200 278487
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 19:01:32
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 19:01:32] "GET /entidade/visualizar/5/ HTTP/1.1" 200 278491
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:32] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/scripts/protocolo/protocolo.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/scripts/padrao/controle_botoes.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/angular-1.5.8/angular.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:33] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[10/Jan/2017 19:01:34] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0
[10/Jan/2017 19:01:34] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 19:04:32
Django version 1.9.7, using settings 'sistema_contabil.settings'
Starting development server at http://localhost:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 19:04:50] "GET /entidade/visualizar/3/ HTTP/1.1" 200 280044
[10/Jan/2017 19:06:05] "GET /entidade/visualizar/3/ HTTP/1.1" 200 280044
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/jquery/jquery-2.2.0.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/icones/css/font-awesome.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/adminlte/css/AdminLTE.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/adminlte/css/skins/skin-blue.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:06] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/css/dataTables.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/datatable/plugins/responsivo/Responsive-2.0.2/css/responsive.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/css/select.bootstrap.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/datatable/DataTables-1.10.11/js/dataTables.bootstrap.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/datatable/plugins/select/Select-1.1.2/js/dataTables.select.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/jquery/jquery-ui-1.11.4/jquery-ui.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.css HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/jquery/jquery-editable-select/jquery.editable-select.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/scripts/padrao/controle_botoes.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/scripts/protocolo/protocolo.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/angular-1.5.8/angular.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/adminlte/js/app.min.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/scripts/padrao/controle_componentes.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/scripts/mask.js HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/imagens/avatar5.png HTTP/1.1" 304 0
[10/Jan/2017 19:06:07] "GET /arquivos_estaticos/imagens/logo.png HTTP/1.1" 304 0

Process finished with exit code 0
